"""Generate/check target-specific pip requirements from pyproject.toml.

Run with Python >=3.10 and pip >=23. Python 3.10 additionally needs tomli.
Generation resolves in pip's dry-run mode; checking is entirely offline.
"""

import argparse
import hashlib
import json
import platform
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def target():
    return {
        "python": f"{sys.version_info.major}.{sys.version_info.minor}",
        "implementation": platform.python_implementation(),
        "system": platform.system(),
        "machine": platform.machine(),
        "os_release": platform.release(),
    }


def manifest_digest(root):
    return hashlib.sha256((root / "pyproject.toml").read_bytes()).hexdigest()


def read_config(root):
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib
    return tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))


def render_lock(report, digest, profile):
    if report.get("version") != "1":
        raise ValueError("Unsupported pip installation report version")
    lines = [
        "# Generated by tools/lock_environment.py; do not edit.",
        "# target: " + json.dumps(target(), sort_keys=True),
        "# pyproject-sha256: " + digest,
        "# profile: " + profile,
        "# pip-version: " + report["pip_version"],
        "",
    ]
    entries = []
    for item in report["install"]:
        name = re.sub(r"[-_.]+", "-", item["metadata"]["name"]).lower()
        if name == "stock-trend-environment":
            continue
        download = item["download_info"]
        if download.get("vcs_info") or download.get("dir_info"):
            raise ValueError(f"Only registry archives can be locked: {name}")
        digest_value = download.get("archive_info", {}).get("hashes", {}).get("sha256", "")
        if not re.fullmatch(r"[a-f0-9]{64}", digest_value):
            raise ValueError(f"Missing sha256 for {name}")
        entries.append(f"{name}=={item['metadata']['version']} --hash=sha256:{digest_value}")
    if not entries:
        raise ValueError("Empty dependency resolution")
    return "\n".join(lines + sorted(entries)) + "\n"


def check_lock(path, root, profile):
    text = path.read_text(encoding="utf-8")
    expected = {
        "target": json.dumps(target(), sort_keys=True),
        "pyproject-sha256": manifest_digest(root),
        "profile": profile,
    }
    for key, value in expected.items():
        if f"# {key}: {value}" not in text.splitlines():
            raise ValueError(f"Lock {key} differs; regenerate for this manifest/target/profile")
    requirements = [line for line in text.splitlines() if line and not line.startswith("#")]
    if not requirements or any(not re.fullmatch(
        r"[a-z0-9][a-z0-9-]*==[^\s]+ --hash=sha256:[a-f0-9]{64}", line
    ) for line in requirements):
        raise ValueError("Lock must contain exact versions and archive sha256 hashes")
    from packaging.requirements import Requirement
    from packaging.utils import canonicalize_name
    pinned = {}
    for line in requirements:
        name, version = line.split(" --hash=", 1)[0].split("==", 1)
        if name in pinned:
            raise ValueError(f"Duplicate locked package: {name}")
        pinned[name] = version
    config = read_config(root)
    project = config["project"]
    declared = list(project.get("dependencies", [])) + config.get("build-system", {}).get("requires", [])
    if profile == "all":
        # all is a convenience extra referencing this project's other extras.
        extras = project.get("optional-dependencies", {})
        for declaration in extras.get("all", []):
            requirement = Requirement(declaration)
            if canonicalize_name(requirement.name) == canonicalize_name(project["name"]):
                for extra in requirement.extras:
                    declared.extend(extras[extra])
            else:
                declared.append(declaration)
    for declaration in declared:
        requirement = Requirement(declaration)
        if requirement.marker and not requirement.marker.evaluate():
            continue
        name = canonicalize_name(requirement.name)
        if name not in pinned or pinned[name] not in requirement.specifier:
            raise ValueError(f"Lock missing or incompatible declared dependency: {declaration}")


def generate(path, root, profile):
    config = read_config(root)
    requirement = str(root) + ("[all]" if profile == "all" else "")
    with tempfile.TemporaryDirectory(prefix="stock-trend-lock-") as temporary:
        report_path = Path(temporary) / "report.json"
        subprocess.run([
            sys.executable, "-m", "pip", "install", "--disable-pip-version-check",
            "--dry-run", "--ignore-installed",
            "--report", str(report_path), requirement,
            *config["build-system"]["requires"],
        ], check=True, stdout=sys.stderr)
        content = render_lock(json.loads(report_path.read_text()), manifest_digest(root), profile)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=("core", "all"), default="all")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true", help="Offline manifest/target/format check")
    args = parser.parse_args()
    if sys.version_info < (3, 10):
        parser.error("Python >=3.10 required")
    try:
        if args.check:
            check_lock(args.output, ROOT, args.profile)
        else:
            generate(args.output, ROOT, args.profile)
    except (ValueError, OSError, ImportError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"Environment lock failed: {exc}\n")
    print(f"{'Checked' if args.check else 'Generated'} {args.output}")


if __name__ == "__main__":
    main()
